id: ID3D4DFDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:42:59+00:00'
last_modified: '2022-06-08T12:31:22.158900+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC237
  title: ཇོ་ནང་པའི་ལུགས་ཀྱི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BC76:
      image_group_id: I2PD18113
      title: ''
      total_pages: 810
      order: 1
      base_file: BC76.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
