id: P009643
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC237
  title: ཇོ་ནང་པའི་ལུགས་ཀྱི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    5dbcdc1aad4c4f27a9987b1a67ddc86a:
      image_group_id: I2PD18113
      title: ''
      volume_number: 1
      total_pages: 810
      base_file: v001.txt
